package my.talabatproject;


import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yasmi
 */
public class addmeal extends javax.swing.JFrame {

    /**
     *
     */
    public addmeal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Lbl_restaurant_name = new javax.swing.JLabel();
        Lbl_price = new javax.swing.JLabel();
        Lbl_meal_description = new javax.swing.JLabel();
        Btn_confirm = new javax.swing.JButton();
        Txt_add_meal_price = new javax.swing.JTextField();
        Lbl_close = new javax.swing.JLabel();
        Lbl_minimize = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArea_meal_description = new javax.swing.JTextArea();
        Txt_add_meal_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Lbl_image_upload = new javax.swing.JLabel();
        Txt_path = new javax.swing.JTextField();
        Lbl_meal_name1 = new javax.swing.JLabel();
        Txt_restaurant_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Candara", 1, 43)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Meal");
        jLabel5.setAutoscrolls(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 237, 60));

        Lbl_restaurant_name.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_restaurant_name.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_restaurant_name.setForeground(new java.awt.Color(255, 102, 51));
        Lbl_restaurant_name.setText("Restaurant Name");
        jPanel1.add(Lbl_restaurant_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 42));

        Lbl_price.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        Lbl_price.setForeground(new java.awt.Color(255, 102, 51));
        Lbl_price.setText("Meal Price");
        jPanel1.add(Lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, 38));

        Lbl_meal_description.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_meal_description.setForeground(new java.awt.Color(255, 102, 51));
        Lbl_meal_description.setText("Meal Description");
        jPanel1.add(Lbl_meal_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 170, 42));

        Btn_confirm.setBackground(new java.awt.Color(255, 102, 51));
        Btn_confirm.setFont(new java.awt.Font("Sitka Text", 1, 22)); // NOI18N
        Btn_confirm.setForeground(new java.awt.Color(243, 245, 246));
        Btn_confirm.setText("Confirm");
        Btn_confirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_confirmActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 220, 55));

        Txt_add_meal_price.setBackground(new java.awt.Color(238, 238, 238));
        Txt_add_meal_price.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Txt_add_meal_price.setForeground(new java.awt.Color(51, 51, 51));
        Txt_add_meal_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Txt_add_meal_price.setBorder(null);
        Txt_add_meal_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_add_meal_priceActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_add_meal_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 197, 40));

        Lbl_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lbl_close.setForeground(new java.awt.Color(255, 51, 0));
        Lbl_close.setText("X");
        Lbl_close.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lbl_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_closeMouseClicked(evt);
            }
        });
        jPanel1.add(Lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 24, 23));

        Lbl_minimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_minimize.setForeground(new java.awt.Color(204, 204, 204));
        Lbl_minimize.setText("-");
        jPanel1.add(Lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 22, -1));

        TxtArea_meal_description.setBackground(new java.awt.Color(238, 238, 238));
        TxtArea_meal_description.setColumns(20);
        TxtArea_meal_description.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtArea_meal_description.setForeground(new java.awt.Color(51, 51, 51));
        TxtArea_meal_description.setRows(5);
        TxtArea_meal_description.setBorder(null);
        jScrollPane1.setViewportView(TxtArea_meal_description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 320, 146));

        Txt_add_meal_name.setBackground(new java.awt.Color(238, 238, 238));
        Txt_add_meal_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Txt_add_meal_name.setBorder(null);
        Txt_add_meal_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_add_meal_nameActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_add_meal_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 197, 39));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Upload Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 190, 40));

        Lbl_image_upload.setText("Lbl_image_upload");
        Lbl_image_upload.setMaximumSize(new java.awt.Dimension(52, 13));
        Lbl_image_upload.setMinimumSize(new java.awt.Dimension(52, 13));
        Lbl_image_upload.setPreferredSize(new java.awt.Dimension(52, 13));
        jPanel1.add(Lbl_image_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 250, 170));

        Txt_path.setText("Txt_path");
        jPanel1.add(Txt_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 340, 70));

        Lbl_meal_name1.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_meal_name1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        Lbl_meal_name1.setForeground(new java.awt.Color(255, 102, 51));
        Lbl_meal_name1.setText("Meal Name");
        jPanel1.add(Lbl_meal_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 42));

        Txt_restaurant_name.setBackground(new java.awt.Color(238, 238, 238));
        Txt_restaurant_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Txt_restaurant_name.setBorder(null);
        Txt_restaurant_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_restaurant_nameActionPerformed(evt);
            }
        });
        jPanel1.add(Txt_restaurant_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 197, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_confirmActionPerformed
     RestaurantOwner.AddMeal(Txt_add_meal_name.getText(), Integer.parseInt(Txt_add_meal_price.getText()), TxtArea_meal_description.getText(),Txt_restaurant_name.getText(),Txt_path.getText());
     JOptionPane.showMessageDialog(null,"Your Meal is Added");
    }//GEN-LAST:event_Btn_confirmActionPerformed
    
    private void Txt_add_meal_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_add_meal_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_add_meal_priceActionPerformed

    private void Lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Lbl_closeMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new  FileNameExtensionFilter("5 supported extensions","jpg","jpeg","gif","png","jfif");
        chooser.setFileFilter(filter);
       int selected = chooser.showOpenDialog(null);    
       if(selected == JFileChooser.APPROVE_OPTION){
            File file = chooser.getSelectedFile();
        String fileName = file.getAbsolutePath();
        Txt_path.setText(fileName);
           JOptionPane.showMessageDialog(null, fileName);
          ImageIcon image=new ImageIcon(fileName);
            Image imfit=image.getImage();
            Image imgfit=imfit.getScaledInstance(Lbl_image_upload.getWidth(),Lbl_image_upload.getHeight(),Image.SCALE_SMOOTH);
           Lbl_image_upload.setIcon(new ImageIcon(imfit));
       
       }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_add_meal_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_add_meal_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_add_meal_nameActionPerformed

    private void Txt_restaurant_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_restaurant_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_restaurant_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_confirm;
    private javax.swing.JLabel Lbl_close;
    private javax.swing.JLabel Lbl_image_upload;
    private javax.swing.JLabel Lbl_meal_description;
    private javax.swing.JLabel Lbl_meal_name1;
    private javax.swing.JLabel Lbl_minimize;
    private javax.swing.JLabel Lbl_price;
    private javax.swing.JLabel Lbl_restaurant_name;
    private javax.swing.JTextArea TxtArea_meal_description;
    private javax.swing.JTextField Txt_add_meal_name;
    private javax.swing.JTextField Txt_add_meal_price;
    private javax.swing.JTextField Txt_path;
    private javax.swing.JTextField Txt_restaurant_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
