/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.talabatproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author Yasmeen Abdelaziz
 */
public class BrowseOrders extends javax.swing.JFrame {

    /**
     * Creates new form BrowseOrders
     */
    public BrowseOrders() throws SQLException {
        initComponents();
        open();

    }
    String customername = Customer.getCustomername();

    public void open() throws SQLException {
        Connection con = my.talabatproject.Db.connect();
        try (PreparedStatement ps = con.prepareStatement("select * from Orders WHERE customer=?")) {
            ps.setString(1, customername);
            ResultSet r = ps.executeQuery();
            r.next();
            Lbl_restaurantName1.setText(r.getString("restaurant_name"));
            Lbl_totalQuantity1.setText(r.getString("MealQuantity"));
            Lbl_totalPrice1.setText(r.getString("total price"));
            Lbl_dispalyOrderDate1.setText(r.getString("order_date"));
          
            r.next();
            Lbl_restaurantName2.setText(r.getString("restaurant_name"));
            Lbl_totalQuantity2.setText(r.getString("MealQuantity"));
            Lbl_totalPrice2.setText(r.getString("total price"));
            Lbl_dispalyOrderDate2.setText(r.getString("order_date"));
        } catch (SQLException ex) {
            ex.getMessage();
        } finally {
            con.close();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lbl_restaurantName1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Lbl_totalAmount1 = new javax.swing.JLabel();
        Lbl_EGP1 = new javax.swing.JLabel();
        Lbl_totalPrice1 = new javax.swing.JLabel();
        times3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lbl_totalQuantity1 = new javax.swing.JLabel();
        Lbl_orderDate1 = new javax.swing.JLabel();
        Lbl_dispalyOrderDate2 = new javax.swing.JLabel();
        Lbl_restaurantName2 = new javax.swing.JLabel();
        Lbl_totalAmount2 = new javax.swing.JLabel();
        Lbl_totalQuantity2 = new javax.swing.JLabel();
        Lbl_orderDate2 = new javax.swing.JLabel();
        Lbl_dispalyOrderDate1 = new javax.swing.JLabel();
        Lbl_EGP2 = new javax.swing.JLabel();
        Lbl_totalPrice2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(231, 231, 231));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order History");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        Lbl_restaurantName1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lbl_restaurantName1.setText("restaurant name");
        Lbl_restaurantName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_restaurantName1MouseClicked(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(231, 231, 231));
        jLabel8.setText("______________________________________________________________________");

        jLabel10.setForeground(new java.awt.Color(231, 231, 231));
        jLabel10.setText("______________________________________________________________________");

        Lbl_totalAmount1.setBackground(new java.awt.Color(0, 0, 0));
        Lbl_totalAmount1.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        Lbl_totalAmount1.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_totalAmount1.setText("Total amount");

        Lbl_EGP1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Lbl_EGP1.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_EGP1.setText("EGP ");

        Lbl_totalPrice1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Lbl_totalPrice1.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_totalPrice1.setText("0.00");

        times3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        times3.setForeground(new java.awt.Color(255, 51, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("<");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        Lbl_totalQuantity1.setBackground(new java.awt.Color(255, 51, 0));
        Lbl_totalQuantity1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Lbl_totalQuantity1.setForeground(new java.awt.Color(255, 51, 0));
        Lbl_totalQuantity1.setText("x");

        Lbl_orderDate1.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        Lbl_orderDate1.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_orderDate1.setText("Order Date");

        Lbl_dispalyOrderDate2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Lbl_dispalyOrderDate2.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_dispalyOrderDate2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_dispalyOrderDate2.setText("Date");

        Lbl_restaurantName2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lbl_restaurantName2.setText("restaurant name");
        Lbl_restaurantName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_restaurantName2MouseClicked(evt);
            }
        });

        Lbl_totalAmount2.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        Lbl_totalAmount2.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_totalAmount2.setText("Total amount");

        Lbl_totalQuantity2.setBackground(new java.awt.Color(255, 51, 0));
        Lbl_totalQuantity2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Lbl_totalQuantity2.setForeground(new java.awt.Color(255, 51, 0));
        Lbl_totalQuantity2.setText("x");

        Lbl_orderDate2.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        Lbl_orderDate2.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_orderDate2.setText("Order Date");

        Lbl_dispalyOrderDate1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Lbl_dispalyOrderDate1.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_dispalyOrderDate1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Lbl_dispalyOrderDate1.setText("Date");

        Lbl_EGP2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Lbl_EGP2.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_EGP2.setText("EGP ");

        Lbl_totalPrice2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Lbl_totalPrice2.setForeground(new java.awt.Color(102, 102, 102));
        Lbl_totalPrice2.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Lbl_totalAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(Lbl_totalQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(Lbl_EGP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_totalPrice1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Lbl_orderDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(times3))
                    .addComponent(Lbl_dispalyOrderDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_orderDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_totalAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Lbl_totalQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(Lbl_EGP2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_totalPrice2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Lbl_dispalyOrderDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Lbl_restaurantName1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Lbl_restaurantName2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addComponent(Lbl_restaurantName1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Lbl_totalQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_EGP1)
                            .addComponent(Lbl_totalPrice1)))
                    .addComponent(Lbl_totalAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(times3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_orderDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_dispalyOrderDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel10)
                .addGap(44, 44, 44)
                .addComponent(Lbl_restaurantName2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(Lbl_orderDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Lbl_totalAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_totalPrice2)
                                    .addComponent(Lbl_EGP2))
                                .addGap(3, 3, 3)
                                .addComponent(Lbl_dispalyOrderDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Lbl_totalQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Menu back_to_Menu = new Menu();
        this.dispose();
        back_to_Menu.setVisible(true);
        back_to_Menu.pack();
        back_to_Menu.setLocationRelativeTo(null);
        back_to_Menu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void Lbl_restaurantName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_restaurantName2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lbl_restaurantName2MouseClicked

    private void Lbl_restaurantName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_restaurantName1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lbl_restaurantName1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowseOrders.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowseOrders.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowseOrders.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowseOrders.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BrowseOrders().setVisible(true);
                } catch (SQLException ex) {
                    ex.getMessage();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_EGP1;
    private javax.swing.JLabel Lbl_EGP2;
    private javax.swing.JLabel Lbl_dispalyOrderDate1;
    private javax.swing.JLabel Lbl_dispalyOrderDate2;
    private javax.swing.JLabel Lbl_orderDate1;
    private javax.swing.JLabel Lbl_orderDate2;
    public javax.swing.JLabel Lbl_restaurantName1;
    public javax.swing.JLabel Lbl_restaurantName2;
    private javax.swing.JLabel Lbl_totalAmount1;
    private javax.swing.JLabel Lbl_totalAmount2;
    public javax.swing.JLabel Lbl_totalPrice1;
    public javax.swing.JLabel Lbl_totalPrice2;
    public javax.swing.JLabel Lbl_totalQuantity1;
    public javax.swing.JLabel Lbl_totalQuantity2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel times3;
    // End of variables declaration//GEN-END:variables
}
