/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.talabatproject;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author yasmi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entered_Name = new javax.swing.JTextField();
        Lbl_username = new javax.swing.JLabel();
        Lbl_password = new javax.swing.JLabel();
        Entered_Password = new javax.swing.JPasswordField();
        loginowner = new javax.swing.JButton();
        Lbl = new javax.swing.JLabel();
        Regis = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        Lbl_minimize = new javax.swing.JLabel();
        Lbl_createaccout = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        Lbl_user_image = new javax.swing.JLabel();
        Lbl_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 62, 80));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 5, true), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(435, 429));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entered_Name.setBackground(new java.awt.Color(241, 241, 241));
        Entered_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Entered_Name.setForeground(new java.awt.Color(51, 51, 51));
        Entered_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entered_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Entered_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 38));

        Lbl_username.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        Lbl_username.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_username.setText("User name");
        jPanel1.add(Lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 40));

        Lbl_password.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        Lbl_password.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_password.setText("Password");
        jPanel1.add(Lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 120, 40));

        Entered_Password.setBackground(new java.awt.Color(241, 241, 241));
        Entered_Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Entered_Password.setForeground(new java.awt.Color(51, 51, 51));
        Entered_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entered_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entered_PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Entered_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, 40));

        loginowner.setBackground(new java.awt.Color(0, 102, 255));
        loginowner.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        loginowner.setForeground(new java.awt.Color(255, 255, 255));
        loginowner.setText("Log in as Owner");
        loginowner.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginowner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginownerActionPerformed(evt);
            }
        });
        jPanel1.add(loginowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 310, 51));

        Lbl.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Lbl.setForeground(new java.awt.Color(51, 51, 51));
        Lbl.setText("Don't have an account?");
        Lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        Regis.setBackground(new java.awt.Color(255, 90, 0));
        Regis.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Regis.setForeground(new java.awt.Color(255, 90, 0));
        Regis.setText("Create an account");
        Regis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisMouseClicked(evt);
            }
        });
        jPanel1.add(Regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 90, 0));
        exit.setText("X");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 11, 30, 30));

        Lbl_minimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_minimize.setForeground(new java.awt.Color(204, 204, 204));
        Lbl_minimize.setText("-");
        Lbl_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 30, 30));

        Lbl_createaccout.setForeground(new java.awt.Color(255, 90, 0));
        Lbl_createaccout.setText("_________________");
        jPanel1.add(Lbl_createaccout, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 120, 20));

        login.setBackground(new java.awt.Color(255, 90, 0));
        login.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("    Log in as Customer ");
        login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 310, 51));

        Lbl_user_image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yasmeen Abdelaziz\\Downloads\\Webp.net-resizeimage (2).png")); // NOI18N
        Lbl_user_image.setPreferredSize(new java.awt.Dimension(112, 105));
        jPanel1.add(Lbl_user_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 80));

        Lbl_login.setBackground(new java.awt.Color(42, 62, 80));
        Lbl_login.setFont(new java.awt.Font("Cambria Math", 1, 42)); // NOI18N
        Lbl_login.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_login.setText("Log in");
        jPanel1.add(Lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 233, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entered_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entered_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entered_NameActionPerformed

    private void Entered_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entered_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entered_PasswordActionPerformed

    private void loginownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginownerActionPerformed

        if (evt.getSource() == loginowner) {
            RestaurantOwner res = new RestaurantOwner();
            int i = res.login(Entered_Name.getText(), Entered_Password.getText());
            System.out.println(my.talabatproject.Db.getres());
            switch (i) {
                case 1:

                    this.dispose();
                    Resturant_edit edit;
                     {
                        try {
                            edit = new Resturant_edit();

                            edit.setVisible(true);
                            edit.pack();
                            edit.setLocationRelativeTo(null);
                            edit.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        } catch (SQLException ex) {
                            ex.getMessage();
                        }
                    }
                    break;

                case -1:
                    JOptionPane.showMessageDialog(this, "Incorrect Passord");
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "Login Fail");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_loginownerActionPerformed

    private void RegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisMouseClicked

        // TODO add your handling code here: 
        this.setVisible(false);
        Register rog = new Register();
        rog.setVisible(true);
        rog.setLocationRelativeTo(null);

    }//GEN-LAST:event_RegisMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:

        if (evt.getSource() == login) {
            Customer cus = new Customer();
            int i = cus.login(Entered_Name.getText(), Entered_Password.getText());
            System.out.println(i);
            switch (i) {
                case 1:
                    this.dispose();
                    Menu rog;
                    rog = new Menu();
                    rog.setVisible(true);
                    rog.setLocationRelativeTo(null);
                    break;
                case -1:
                    JOptionPane.showMessageDialog(null, "Incorrect Passord");
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "Login Fail");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Entered_Name;
    private javax.swing.JPasswordField Entered_Password;
    private javax.swing.JLabel Lbl;
    private javax.swing.JLabel Lbl_createaccout;
    private javax.swing.JLabel Lbl_login;
    private javax.swing.JLabel Lbl_minimize;
    private javax.swing.JLabel Lbl_password;
    private javax.swing.JLabel Lbl_user_image;
    private javax.swing.JLabel Lbl_username;
    private javax.swing.JLabel Regis;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton loginowner;
    // End of variables declaration//GEN-END:variables
}
