package my.talabatproject;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Basant
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel_header = new javax.swing.JPanel();
        Lbl_talabat_logo = new javax.swing.JLabel();
        Lbl_exit = new javax.swing.JLabel();
        Lbl_minimiza = new javax.swing.JLabel();
        Lbl_order_history = new javax.swing.JLabel();
        jPanel_main = new javax.swing.JPanel();
        jPanel_all_restaurant = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Txt_search = new javax.swing.JTextField();
        jPanel_buffalobuger = new javax.swing.JPanel();
        Lbl_image_buf = new javax.swing.JLabel();
        bufflo = new javax.swing.JLabel();
        panel_papajohnss = new javax.swing.JPanel();
        Lbl_image_papajohns = new javax.swing.JLabel();
        Lbl_papajohns = new javax.swing.JLabel();
        jPanel_kfc = new javax.swing.JPanel();
        Lbl_image_kfc = new javax.swing.JLabel();
        Lbl_kfc = new javax.swing.JLabel();
        jPanel_mcdonalds = new javax.swing.JPanel();
        Lbl_image_mcdonalds = new javax.swing.JLabel();
        Lbl_mac = new javax.swing.JLabel();
        search = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(812, 960));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_header.setBackground(new java.awt.Color(255, 90, 0));
        jPanel_header.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true)));
        jPanel_header.setMaximumSize(new java.awt.Dimension(798, 90));
        jPanel_header.setMinimumSize(new java.awt.Dimension(798, 90));
        jPanel_header.setPreferredSize(new java.awt.Dimension(798, 90));
        jPanel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_talabat_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/talabatproject/images/talabatt_Easy-Resize.com (1).jpg"))); // NOI18N
        Lbl_talabat_logo.setText("jLabel1");
        jPanel_header.add(Lbl_talabat_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 274, 108));

        Lbl_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lbl_exit.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_exit.setText("X");
        Lbl_exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_exitMouseClicked(evt);
            }
        });
        jPanel_header.add(Lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 10, 28, 29));

        Lbl_minimiza.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_minimiza.setForeground(new java.awt.Color(204, 204, 204));
        Lbl_minimiza.setText("-");
        Lbl_minimiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_minimiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_minimizaMouseClicked(evt);
            }
        });
        jPanel_header.add(Lbl_minimiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 10, 21, -1));

        Lbl_order_history.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_order_history.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lbl_order_history.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_order_history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_order_history.setText("Order History");
        Lbl_order_history.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        Lbl_order_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_order_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_order_historyMouseClicked(evt);
            }
        });
        jPanel_header.add(Lbl_order_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 168, 51));

        getContentPane().add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 130));

        jPanel_main.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_main.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true)));

        jPanel_all_restaurant.setBackground(new java.awt.Color(246, 246, 246));
        jPanel_all_restaurant.setForeground(new java.awt.Color(171, 170, 171));

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 0, 24)); // NOI18N
        jLabel3.setText("All Restaurants");

        javax.swing.GroupLayout jPanel_all_restaurantLayout = new javax.swing.GroupLayout(jPanel_all_restaurant);
        jPanel_all_restaurant.setLayout(jPanel_all_restaurantLayout);
        jPanel_all_restaurantLayout.setHorizontalGroup(
            jPanel_all_restaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_all_restaurantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        jPanel_all_restaurantLayout.setVerticalGroup(
            jPanel_all_restaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_all_restaurantLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        Txt_search.setForeground(new java.awt.Color(102, 102, 102));
        Txt_search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jPanel_buffalobuger.setBackground(new java.awt.Color(246, 246, 246));
        jPanel_buffalobuger.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel_buffalobuger.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_buffalobuger.setPreferredSize(new java.awt.Dimension(185, 235));
        jPanel_buffalobuger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_image_buf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/talabatproject/images/buff_Easy-Resize.com.jpg"))); // NOI18N
        jPanel_buffalobuger.add(Lbl_image_buf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 168, 111));

        bufflo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bufflo.setForeground(new java.awt.Color(51, 51, 51));
        bufflo.setText("Buffalo Burger");
        bufflo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bufflo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buffloMouseClicked(evt);
            }
        });
        jPanel_buffalobuger.add(bufflo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 50));

        panel_papajohnss.setBackground(new java.awt.Color(246, 246, 246));
        panel_papajohnss.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_papajohnss.setPreferredSize(new java.awt.Dimension(185, 235));

        Lbl_image_papajohns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/talabatproject/images/d8ffcc30355585.561f001e8a16d (1)_Easy-Resize.com_Easy-Resize.com.jpg"))); // NOI18N

        Lbl_papajohns.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Lbl_papajohns.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_papajohns.setText("Papa Johns");
        Lbl_papajohns.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_papajohns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_papajohnsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_papajohnssLayout = new javax.swing.GroupLayout(panel_papajohnss);
        panel_papajohnss.setLayout(panel_papajohnssLayout);
        panel_papajohnssLayout.setHorizontalGroup(
            panel_papajohnssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_papajohnssLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Lbl_image_papajohns, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(panel_papajohnssLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Lbl_papajohns)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_papajohnssLayout.setVerticalGroup(
            panel_papajohnssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_papajohnssLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_image_papajohns, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Lbl_papajohns, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel_kfc.setBackground(new java.awt.Color(246, 246, 246));
        jPanel_kfc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel_kfc.setPreferredSize(new java.awt.Dimension(185, 235));

        Lbl_image_kfc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/talabatproject/images/KFC_Easy-Resize.com.jpg"))); // NOI18N
        Lbl_image_kfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_image_kfcMouseClicked(evt);
            }
        });

        Lbl_kfc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Lbl_kfc.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_kfc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_kfc.setText("KFC");
        Lbl_kfc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_kfc.setVerifyInputWhenFocusTarget(false);
        Lbl_kfc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_kfcMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_kfcLayout = new javax.swing.GroupLayout(jPanel_kfc);
        jPanel_kfc.setLayout(jPanel_kfcLayout);
        jPanel_kfcLayout.setHorizontalGroup(
            jPanel_kfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_kfcLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Lbl_image_kfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(jPanel_kfcLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Lbl_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_kfcLayout.setVerticalGroup(
            jPanel_kfcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_kfcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_image_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lbl_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel_mcdonalds.setBackground(new java.awt.Color(246, 246, 246));
        jPanel_mcdonalds.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel_mcdonalds.setPreferredSize(new java.awt.Dimension(185, 235));

        Lbl_image_mcdonalds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/talabatproject/images/mac_Easy-Resize.com.jpg"))); // NOI18N

        Lbl_mac.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Lbl_mac.setForeground(new java.awt.Color(51, 51, 51));
        Lbl_mac.setText("Macdonlds");
        Lbl_mac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lbl_mac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_macMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_mcdonaldsLayout = new javax.swing.GroupLayout(jPanel_mcdonalds);
        jPanel_mcdonalds.setLayout(jPanel_mcdonaldsLayout);
        jPanel_mcdonaldsLayout.setHorizontalGroup(
            jPanel_mcdonaldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mcdonaldsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Lbl_image_mcdonalds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(jPanel_mcdonaldsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Lbl_mac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_mcdonaldsLayout.setVerticalGroup(
            jPanel_mcdonaldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mcdonaldsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_image_mcdonalds, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Lbl_mac, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(panel_papajohnss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jPanel_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_buffalobuger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_mcdonalds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel_all_restaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(36, 36, 36))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel_all_restaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_buffalobuger, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_papajohnss, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_mcdonalds, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jPanel_kfc, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 820, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Lbl_exitMouseClicked

    private void Lbl_minimizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_minimizaMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_Lbl_minimizaMouseClicked

    private void Lbl_papajohnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_papajohnsMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Scrolled_Menu papajohns_res;
        try {

            papajohns_res = new Scrolled_Menu("papa johns");
            papajohns_res.Open();
            papajohns_res.setVisible(true);
            papajohns_res.setLocationRelativeTo(null);

        } catch (SQLException ex) {
            ex.getMessage();

        }

    }//GEN-LAST:event_Lbl_papajohnsMouseClicked

    private void Lbl_macMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_macMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Scrolled_Menu mcdonalds_res;
        try {

            mcdonalds_res = new Scrolled_Menu("mcdonalds");
            mcdonalds_res.Open();
            mcdonalds_res.setVisible(true);
            mcdonalds_res.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            ex.getMessage();

        }
    }//GEN-LAST:event_Lbl_macMouseClicked

    private void buffloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buffloMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Scrolled_Menu Buffalo_res;
        try {

            Buffalo_res = new Scrolled_Menu("Buffalo burger");
            Buffalo_res.Open();
            Buffalo_res.setVisible(true);
            Buffalo_res.setLocationRelativeTo(null);

        } catch (SQLException ex) {
            ex.getMessage();

        }

    }//GEN-LAST:event_buffloMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        int searching = RestaurantOwner.chooseRestaurant(Txt_search.getText());
        if (searching == 1) {
            this.dispose();
            Scrolled_Menu Srch_Res;
            try {

                Srch_Res = new Scrolled_Menu();
                Srch_Res.Open();
                Srch_Res.setVisible(true);
                Srch_Res.setLocationRelativeTo(null);

            } catch (SQLException ex) {
                ex.getMessage();

            }

        } else {
            JOptionPane.showMessageDialog(this, "Unavailable Restaurant", "Error", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_searchActionPerformed

    private void Lbl_kfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_kfcMouseClicked

        this.dispose();
        Scrolled_Menu log1;

        try {
            log1 = new Scrolled_Menu("kfc");
            log1.Open();
            log1.setVisible(true);
            log1.setLocationRelativeTo(null);
            log1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        } catch (SQLException ex) {
            ex.getMessage();

        }
    }//GEN-LAST:event_Lbl_kfcMouseClicked

    private void Lbl_image_kfcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_image_kfcMouseClicked

        this.dispose();
        Scrolled_Menu kfc_res;
        try {

            kfc_res = new Scrolled_Menu("kfc");
            kfc_res.Open();
            kfc_res.setVisible(true);
            kfc_res.setLocationRelativeTo(null);
            kfc_res.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        } catch (SQLException ex) {
            ex.getMessage();

        }
    }//GEN-LAST:event_Lbl_image_kfcMouseClicked

    private void Lbl_order_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_order_historyMouseClicked
        // TODO add your handling code here:
        this.dispose();
        BrowseOrders orders;
        try {
            orders = new BrowseOrders();
            orders.setVisible(true);
            orders.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_Lbl_order_historyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_exit;
    private javax.swing.JLabel Lbl_image_buf;
    private javax.swing.JLabel Lbl_image_kfc;
    private javax.swing.JLabel Lbl_image_mcdonalds;
    private javax.swing.JLabel Lbl_image_papajohns;
    public javax.swing.JLabel Lbl_kfc;
    private javax.swing.JLabel Lbl_mac;
    private javax.swing.JLabel Lbl_minimiza;
    private javax.swing.JLabel Lbl_order_history;
    private javax.swing.JLabel Lbl_papajohns;
    private javax.swing.JLabel Lbl_talabat_logo;
    public javax.swing.JTextField Txt_search;
    private javax.swing.JLabel bufflo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_all_restaurant;
    private javax.swing.JPanel jPanel_buffalobuger;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_kfc;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_mcdonalds;
    private javax.swing.JPanel panel_papajohnss;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
