/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.talabatproject;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yasmi
 */
public class Owner extends javax.swing.JFrame {

    /**
     * Creates new form Owner
     */
    public Owner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordercounter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addmeal = new javax.swing.JButton();
        meal1name = new javax.swing.JLabel();
        meal2name = new javax.swing.JLabel();
        meal3name = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        delete1 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        edit3 = new javax.swing.JButton();
        delete3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        desc1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        desc2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Txt_path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        meal3name1 = new javax.swing.JLabel();
        edit4 = new javax.swing.JButton();
        delete4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        desc4 = new javax.swing.JTextArea();
        p4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ordercounter.setBackground(new java.awt.Color(255, 255, 255));
        ordercounter.setPreferredSize(new java.awt.Dimension(650, 761));
        ordercounter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 90, 0));

        addmeal.setBackground(new java.awt.Color(150, 63, 45));
        addmeal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addmeal.setForeground(new java.awt.Color(255, 255, 255));
        addmeal.setText("Add New Meal");
        addmeal.setBorder(null);
        addmeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addmealMouseClicked(evt);
            }
        });
        addmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(addmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(addmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        ordercounter.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        meal1name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        meal1name.setForeground(new java.awt.Color(51, 51, 51));
        ordercounter.add(meal1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 50));

        meal2name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        meal2name.setForeground(new java.awt.Color(51, 51, 51));
        ordercounter.add(meal2name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 230, 50));

        meal3name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        meal3name.setForeground(new java.awt.Color(51, 51, 51));
        ordercounter.add(meal3name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 250, 40));

        p1.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        p1.setForeground(new java.awt.Color(51, 51, 51));
        p1.setBorder(null);
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        ordercounter.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 40, 32));

        p2.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        ordercounter.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 40, -1));

        p3.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });
        ordercounter.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, 40, -1));

        delete1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        ordercounter.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 150, -1, -1));

        edit1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit1.setText("Edit");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        ordercounter.add(edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 150, -1, -1));

        edit2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit2.setText("Edit");
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });
        ordercounter.add(edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        delete2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete2.setText("Delete");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        ordercounter.add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        edit3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit3.setText("Edit");
        edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit3ActionPerformed(evt);
            }
        });
        ordercounter.add(edit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, -1));

        delete3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete3.setText("Delete");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        ordercounter.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("EGP");
        ordercounter.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 940, -1, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("EGP");
        ordercounter.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 30));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("EGP");
        ordercounter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, -1, 30));

        desc3.setColumns(20);
        desc3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        desc3.setRows(5);
        jScrollPane2.setViewportView(desc3);

        ordercounter.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 510, 110));

        desc1.setColumns(20);
        desc1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        desc1.setRows(5);
        jScrollPane4.setViewportView(desc1);

        ordercounter.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 490, 110));

        desc2.setColumns(20);
        desc2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        desc2.setRows(5);
        jScrollPane5.setViewportView(desc2);

        ordercounter.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 500, 110));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel1.setText("PATH");
        ordercounter.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 40, 30));

        Txt_path.setText("Txt_path");
        ordercounter.add(Txt_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 180, 30));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ordercounter.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 80, 30));

        meal3name1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        meal3name1.setForeground(new java.awt.Color(51, 51, 51));
        ordercounter.add(meal3name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, 250, 40));

        edit4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit4.setText("Edit");
        edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit4ActionPerformed(evt);
            }
        });
        ordercounter.add(edit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 780, -1, -1));

        delete4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete4.setText("Delete");
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });
        ordercounter.add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 780, -1, -1));

        desc4.setColumns(20);
        desc4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        desc4.setRows(5);
        jScrollPane3.setViewportView(desc4);

        ordercounter.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 820, 510, 110));

        p4.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });
        ordercounter.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 940, 40, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("EGP");
        ordercounter.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, -1, 30));

        jScrollPane1.setViewportView(ordercounter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  String resName = my.talabatproject.Db.restaurantName;

    public void Open() throws SQLException {
        try {
            Connection con = my.talabatproject.Db.connect();
            PreparedStatement ps = null;
            ps = con.prepareStatement("select * from Meals WHERE restaurant_name=?");
            ps.setString(1, my.talabatproject.Db.getres());
            ps.execute();
            ResultSet r = ps.executeQuery();
            r.next();
            meal1name.setText(r.getString("meal_name"));
            desc1.setText(r.getString("meal_description"));
            p1.setText(r.getString("meal_price"));
            Txt_path.setText(r.getString("meal_image"));
            r.next();
            meal2name.setText(r.getString("meal_name"));
            desc2.setText(r.getString("meal_description"));
            p2.setText(r.getString("meal_price"));
            r.next();
            meal3name.setText(r.getString("meal_name"));
            desc3.setText(r.getString("meal_description"));
            p3.setText(r.getString("meal_price"));
            r.next();
            meal3name1.setText(r.getString("meal_name"));
            desc4.setText(r.getString("meal_description"));
            p4.setText(r.getString("meal_price"));
            con.close();
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }
int Image_Upload = -1;
    private void addmealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmealMouseClicked
        // TODO add your handling code here:
        this.dispose();
        addmeal add = new addmeal();
        add.setVisible(true);
        add.pack();
        add.setLocationRelativeTo(null);
        add.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_addmealMouseClicked

    private void addmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmealActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_addmealActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        String name = meal1name.getText();
        try {
RestaurantOwner res=new RestaurantOwner();
            res.delete(name);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        // TODO add your handling code here:

        int price = Integer.parseInt(p1.getText());
        String desc = desc1.getText(), name = meal1name.getText();
        if (Image_Upload == -1) {
            my.talabatproject.Db.Update(price, desc, name);
        } else {
            String image = Txt_path.getText();
            my.talabatproject.Db.Update(price, desc, name, image);
        }
    }//GEN-LAST:event_edit1ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(p2.getText());
        String desc = desc2.getText(), name = meal2name.getText();

        my.talabatproject.Db.Update(price, desc, name);
    }//GEN-LAST:event_edit2ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        String name = meal2name.getText();
        try {
          RestaurantOwner res=new RestaurantOwner();
            res.delete(name);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_delete2ActionPerformed

    private void edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit3ActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(p3.getText());
        String desc = desc3.getText(), name = meal3name.getText();
        System.out.println(price);
        System.out.println(desc);
        System.out.println(name);
        my.talabatproject.Db.Update(price, desc, name);
    }//GEN-LAST:event_edit3ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        // TODO add your handling code here:
        String name = meal3name.getText();
        try {
          RestaurantOwner res=new RestaurantOwner();
            res.delete(name);
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_delete3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (evt.getSource() == jButton1) {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("5 supported extensions", "jpg", "jpeg", "gif", "png", "jfif");
            chooser.setFileFilter(filter);
            int selected = chooser.showOpenDialog(null);
            if (selected == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                String fileName = file.getAbsolutePath();
                Txt_path.setText(fileName);
                JOptionPane.showMessageDialog(null, fileName);
                ImageIcon image = new ImageIcon(fileName);
                Image imfit = image.getImage();
           

            }
            Image_Upload = 1;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit4ActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(p4.getText());
        String desc = desc4.getText(), name = meal3name1.getText();
        my.talabatproject.Db.Update(price, desc, name);
    }//GEN-LAST:event_edit4ActionPerformed

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        // TODO add your handling code here:
        String name = meal3name1.getText();
        try {
    RestaurantOwner res=new RestaurantOwner();
            res.delete(name);
        } catch (SQLException ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_delete4ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt_path;
    private javax.swing.JButton addmeal;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JButton delete4;
    private javax.swing.JTextArea desc1;
    private javax.swing.JTextArea desc2;
    private javax.swing.JTextArea desc3;
    private javax.swing.JTextArea desc4;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel meal1name;
    private javax.swing.JLabel meal2name;
    private javax.swing.JLabel meal3name;
    private javax.swing.JLabel meal3name1;
    private javax.swing.JPanel ordercounter;
    public javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    // End of variables declaration//GEN-END:variables
}
